development:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: lobsters_dev
  socket: /tmp/mysql.sock
  username: dev_username
  password: dev_password
  
test:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: lobsters_test
  socket: /tmp/mysql.sock
  username: test_username
  password: test_password

production:
  adapter: mysql2
  url: <%= ENV['DATABASE_URL'] %>
