development:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: lobsters_dev
  host: 127.0.0.1
  username: tannakartikey
  password: ''
  
test:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: lobsters_test

production:
  adapter: mysql2
  url: <%= ENV['DATABASE_URL'] %>
  host: 127.0.0.1
  username: tannakartikey
  password: ''
